#!/bin/bash

function git_remote {
  remote=$(git remote get-url --push origin 2>>/dev/null )
  ok=$?
  if [[ $ok == 0 ]]; then
    echo $remote
  else
    echo none
  fi
}

function git_head {
  local commit_hash=$(git rev-parse --short HEAD)
  local tag_name=$(git describe --exact-match --tags $commit_hash 2>/dev/null)
  if [ -z "$tag_name" ]; then
    echo $commit_hash
  else
    echo $tag_name
  fi
}

function remove_volumes {
  docker volume rm $(docker volume ls -q --filter name="${1}_")
}

function net_exists {
  docker network inspect "$1" > /dev/null
  return $?
}

function command_down {
  docker stack rm "${STACK}"
  sleep 10
  while net_exists "${STACK}_lan"; do
    :
  done
  remove_volumes ${STACK}
}

function command_up {
  docker stack deploy --detach=true -c "${COMPOSE}" "${STACK}"
}

function command_reset {
  command_down
  command_up
}

function command_help {
  echo "HELP"
}

export COMPOSE=(*.stack.yml)
export STACK="${COMPOSE/%.stack.yml}"
export REMOTE=$(git_remote)
export VERSION=$(git_head)
echo "managing $STACK $REMOTE $VERSION"

CMD="command_${1:-help}"
shift
$CMD $@
